very conservative Pipfile.lock to fix import bug
When pipenv upgraded all dependencies after installing pygal, tests
failed due to errors like:

    NotImplementedError: Can't perform this operation for unregistered loader type

coming from citeproc style code, via `pkg_resource`. Still not sure what
the root cause is, as that package itself wasn't upgraded. I tried a bit
of bisecting dependency upgrades but nothing obvious was the cause, and
a full bisection would take forever.